#!/bin/bash

set -e

compile() {

gcc -Wall -Werror -Wextra *.c -o out && ./out

}

simple() {

gcc *.c -o out

}

complete() {

gcc -o2 -Wall -Wextra -Werror *.c -o out && ./out | cat -e

}

out() {

./out | cat -e

}

help() {

cat << _EOF_

 Compile is a tool that automates de procedures of compiling and executing C programs.

 Commands:
	compile		= Compile a program with the expected flags and runs it.

	compile -s	= Compile a program with the minimum posibilities.
			  This option don't runs the program

	compile -o	= It doesn't compile anything. 
			  Just runs the program if theres any output.

	compile -c	= Compile a program with all the posibilites and expected flags.
			  This opttion runs the program.

	compile -help	= Prints this very same text.

_EOF_

}

if [ "$1" == "-c" ]; then
	complete
	exit
fi

if [ "$1" == "-s" ]; then
	simple
	exit
fi

if [ "$1" == "-o" ]; then
	out
	exit
fi

if [ "$1" == "-help" ]; then
	help
	exit
fi

if [ -n "$1" ]; then
	echo "There's have been an error. Try -help to find all posible flags for this script."
	exit
fi

compile
exit
